"""
Learner Journey project - Step 3: run the analysis and export results

Runs every query in 02_analysis.sql against oulad.db and saves:
  outputs/<query_name>.csv            one file per query
  outputs/learner_journey_results.xlsx  one sheet per query + the cleaning log
  outputs/learners_for_dashboard.csv  the modeled table, for Tableau / Power BI

Run from the project folder (after 01_etl.py):
    python3 03_export.py
"""

import re
import sqlite3
from pathlib import Path

import pandas as pd

DB = Path("oulad.db")
OUT = Path("outputs")
OUT.mkdir(exist_ok=True)

sql_text = Path("02_analysis.sql").read_text()
blocks = re.split(r"^-- name:\s*(\w+)\s*$", sql_text, flags=re.M)
queries = {blocks[i]: blocks[i + 1].strip() for i in range(1, len(blocks), 2)}

con = sqlite3.connect(DB)
results = {}
for name, q in queries.items():
    df = pd.read_sql_query(q, con)
    df.to_csv(OUT / f"{name}.csv", index=False)
    results[name] = df
    print(f"\n=== {name} ({len(df)} rows) ===")
    print(df.head(12).to_string(index=False))

# The modeled table, for building the dashboard
learners = pd.read_sql_query("SELECT * FROM learners", con)
learners.to_csv(OUT / "learners_for_dashboard.csv", index=False)
con.close()

with pd.ExcelWriter(OUT / "learner_journey_results.xlsx") as xl:
    log_path = OUT / "cleaning_log.csv"
    if log_path.exists():
        pd.read_csv(log_path).to_excel(xl, sheet_name="cleaning_log", index=False)
    for name, df in results.items():
        df.to_excel(xl, sheet_name=name[:31], index=False)

# RESULTS.md - a readable summary generated from YOUR run, so the numbers in the repo
# always come from the real data, never typed in by hand.
def md_table(df):
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for row in df.itertuples(index=False):
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in row) + " |")
    return "\n".join(lines)

TITLES = {
    "q0_overview": "How learners finish",
    "q1_outcomes_by_course": "Completion and withdrawal by course run",
    "q2_registration_timing": "Does signing up late predict dropping out?",
    "q3_withdrawal_timing": "When do learners withdraw?",
    "q4_first_month_engagement": "Does first-month activity predict the outcome?",
    "q4b_activity_before_start": "Exploring the course before day one",
    "q5_progress": "How far learners get",
    "q7_segments": "Who struggles most",
    "q8_never_started": "Enrolled but never started",
}
md = ["# Results", "", f"_Generated by `03_export.py` from `oulad.db` on {pd.Timestamp.now():%Y-%m-%d}. "
      "Re-run the pipeline to regenerate - do not edit by hand._", ""]
for name, title in TITLES.items():
    if name in results:
        md += [f"## {title}", f"`{name}`", "", md_table(results[name]), ""]
(OUT / "RESULTS.md").write_text("\n".join(md))

print(f"\nSaved {len(results)} result tables to {OUT}/, learner_journey_results.xlsx and RESULTS.md")
print(f"Dashboard source: {OUT/'learners_for_dashboard.csv'} ({len(learners):,} rows)")
